### ISSUE TITLE
Add back button on settings page

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerLabs/project-health#324] opened 2018-03-20 23:08 UTC
## The Problem

There is no back button on the settings page

![image](https://user-images.githubusercontent.com/5948271/37687457-ec10bec4-2c9b-11e8-8da3-4938dc960415.png)

## Expected Behavior

There is a back button back to the homepage

**Comment by samuelli** [comment] 2018-03-20 23:51
Dupe of #256

**Closed by samuelli** 2018-03-20 23:51 UTC

**Comment by TimvdLippe** [comment] 2018-03-21 00:12
Oh I completely missed that one, sorry!
