### ISSUE TITLE
Notification on builds which aren't for the latest commit

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#341] opened 2018-03-21 23:41 UTC
## The Problem
 - Create a pull request which breaks the build
 - Add a commit that fixes the build
 - You'll receive notifications for the first commits builds even though a new commit has been pushed.

## Expected Behavior
You only receive notifications for builds that are the latest commit.

**Comment by gauntface** [comment] 2018-03-22 00:15
Is this not a duplicate of: #336?

**Closed** 2018-03-22 22:19 UTC
